# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ lib, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "telegraf-${version}";
  version = "1.3.1";
  rev = "f93615672b02a41d9bc867bd92bf31c1d777989b";

  goPackagePath = "github.com/influxdata/telegraf";
  excludedPackages = "test";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/influxdata/telegraf";
    sha256 = "0aq001ck07xarqsj2jv87qmad8bf9s0jzf12jrcny829625r10mw";
  };

  goDeps = ./deps.nix;

  meta = with lib; {
    description = "The plugin-driven server agent for collecting & reporting metrics.";
    license = licenses.mit;
    homepage = https://www.influxdata.com/time-series-platform/telegraf/;
    platforms = platforms.linux;
  };
}
