# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ lib, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "telegraf-${version}";
  version = "1.3.5";
  rev = "7192e68b2423997177692834f53cdf171aee1a88";

  goPackagePath = "github.com/influxdata/telegraf";
  excludedPackages = "test";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/influxdata/telegraf";
    sha256 = "087fq6ycdbrfrngg8rvalf1kd3n70zkinmjlsv10b7gmprvmh573";
  };

  goDeps = ./deps.nix;

  meta = with lib; {
    description = "The plugin-driven server agent for collecting & reporting metrics.";
    license = licenses.mit;
    homepage = https://www.influxdata.com/time-series-platform/telegraf/;
    platforms = platforms.linux;
  };
}
